/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Solution: 4613732
*/


public class Problem002{

    private static final long LIMIT = 4000000;

    public static void main(String[] args){
        long sum = 0, next = 1, last = 1;
        while (next + last < LIMIT){
            next += last;
            last = next - last;
            if (next % 2 == 0){
                sum += next;
            }
        }
        System.out.println(sum);
    }
}
